### ISSUE TITLE
タブ、カテゴリ、グループ、サーバ定義の順番指定の対応終わりました。

### ISSUE THREAD

**Issue by turbou** [turbou/TeratermStation#1]
サーバ接続定義の基点ディレクトリ直下にorder.iniを置いて、その中に
順番を上から下に列記するだけで良いです。
注意点としてはこのorder.iniはUTF-8Nである必要が今のところあります。
UTF-8ではなくUTF-8Nです。Javaで読み込む問題ですね。
order.iniに限らず、.txt、.ini、.macroなどの読み込むファイルの文字コードも
設定で指定できるようにしたほうが良いかもしれないです。

**Comment by YoshihitoAso** [comment]
了解です :ok_hand:
