### ISSUE TITLE
yamlについて

### ISSUE THREAD

**Issue by turbou** [turbou/TeratermStation#3]
現在のiniファイルの内容、yaml形式で書けるのはいいですね。
今もそんなに入れ子構造がたくさんあるわけではなく、key = valueで
ほぼ事足りてるのですが、yamlの書き方はわかりやすいですね。
＃JYamlもありましたが、SnakeYamlというほうが新しいみたいです。
とりあえずSnakeYamlでやってみて、loadするだけで良いので楽ですね。
iniでもyamlでも両サポートするでもよくて、一応yaml優先みたいな実装と
するのも良いですが、どうでしょうね。
標準的なライブラリならすんなり採用するのもありですが、SnakeYamlは
どうなのかなぁと思ったり。
なんか他によさ気なフォーマットありますかね。なにかないかなぁ。。

**Comment by YoshihitoAso** [comment]
SnakeYaml ですがApache Storm の設定ファイル読み込みの部分とかにも使われてるみたいですね
https://github.com/apache/storm/search?utf8=%E2%9C%93&q=snakeyaml&type=Code

他も見てみますが、主に使われてそうなので採用でOKな気がします。
その場合、個人的にはyaml一本でも問題無いと思いますね。

**Comment by turbou** [comment]
yaml一本でも良いですね。一通りsettings.yaml, tab.yaml, category.yaml, group.yamlの読み込みに対応しました。クラス構造もそのほうがわかりやすそうです。
それらyamlに相応するBeanクラスもyamlパッケージに４つ追加しました。
で、クラスコメントにyamlの記述イメージも記載しました。とりあえずJavadocは日本語で。
Javadocもそろそろ意識しないといけないですね。

**Comment by YoshihitoAso** [comment]
スッキリしてますね。イイ感じだと思います:+1:
